apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../lab2
  - recommendationservice-v1.yaml
  - recommendationservice-v2.yaml
  - destination-rule.yaml
  - virtual-service.yaml
